require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomersAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomersAddress. As you add validations to CustomersAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomersAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all customers_addresses as @customers_addresses" do
      customers_address = CustomersAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:customers_addresses).should eq([customers_address])
    end
  end

  describe "GET show" do
    it "assigns the requested customers_address as @customers_address" do
      customers_address = CustomersAddress.create! valid_attributes
      get :show, {:id => customers_address.to_param}, valid_session
      assigns(:customers_address).should eq(customers_address)
    end
  end

  describe "GET new" do
    it "assigns a new customers_address as @customers_address" do
      get :new, {}, valid_session
      assigns(:customers_address).should be_a_new(CustomersAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested customers_address as @customers_address" do
      customers_address = CustomersAddress.create! valid_attributes
      get :edit, {:id => customers_address.to_param}, valid_session
      assigns(:customers_address).should eq(customers_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomersAddress" do
        expect {
          post :create, {:customers_address => valid_attributes}, valid_session
        }.to change(CustomersAddress, :count).by(1)
      end

      it "assigns a newly created customers_address as @customers_address" do
        post :create, {:customers_address => valid_attributes}, valid_session
        assigns(:customers_address).should be_a(CustomersAddress)
        assigns(:customers_address).should be_persisted
      end

      it "redirects to the created customers_address" do
        post :create, {:customers_address => valid_attributes}, valid_session
        response.should redirect_to(CustomersAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customers_address as @customers_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomersAddress.any_instance.stub(:save).and_return(false)
        post :create, {:customers_address => {}}, valid_session
        assigns(:customers_address).should be_a_new(CustomersAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomersAddress.any_instance.stub(:save).and_return(false)
        post :create, {:customers_address => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customers_address" do
        customers_address = CustomersAddress.create! valid_attributes
        # Assuming there are no other customers_addresses in the database, this
        # specifies that the CustomersAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomersAddress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => customers_address.to_param, :customers_address => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested customers_address as @customers_address" do
        customers_address = CustomersAddress.create! valid_attributes
        put :update, {:id => customers_address.to_param, :customers_address => valid_attributes}, valid_session
        assigns(:customers_address).should eq(customers_address)
      end

      it "redirects to the customers_address" do
        customers_address = CustomersAddress.create! valid_attributes
        put :update, {:id => customers_address.to_param, :customers_address => valid_attributes}, valid_session
        response.should redirect_to(customers_address)
      end
    end

    describe "with invalid params" do
      it "assigns the customers_address as @customers_address" do
        customers_address = CustomersAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomersAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => customers_address.to_param, :customers_address => {}}, valid_session
        assigns(:customers_address).should eq(customers_address)
      end

      it "re-renders the 'edit' template" do
        customers_address = CustomersAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomersAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => customers_address.to_param, :customers_address => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customers_address" do
      customers_address = CustomersAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => customers_address.to_param}, valid_session
      }.to change(CustomersAddress, :count).by(-1)
    end

    it "redirects to the customers_addresses list" do
      customers_address = CustomersAddress.create! valid_attributes
      delete :destroy, {:id => customers_address.to_param}, valid_session
      response.should redirect_to(customers_addresses_url)
    end
  end

end
