require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LedgersController do

  # This should return the minimal set of attributes required to create a valid
  # Ledger. As you add validations to Ledger, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LedgersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ledgers as @ledgers" do
      ledger = Ledger.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ledgers).should eq([ledger])
    end
  end

  describe "GET show" do
    it "assigns the requested ledger as @ledger" do
      ledger = Ledger.create! valid_attributes
      get :show, {:id => ledger.to_param}, valid_session
      assigns(:ledger).should eq(ledger)
    end
  end

  describe "GET new" do
    it "assigns a new ledger as @ledger" do
      get :new, {}, valid_session
      assigns(:ledger).should be_a_new(Ledger)
    end
  end

  describe "GET edit" do
    it "assigns the requested ledger as @ledger" do
      ledger = Ledger.create! valid_attributes
      get :edit, {:id => ledger.to_param}, valid_session
      assigns(:ledger).should eq(ledger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ledger" do
        expect {
          post :create, {:ledger => valid_attributes}, valid_session
        }.to change(Ledger, :count).by(1)
      end

      it "assigns a newly created ledger as @ledger" do
        post :create, {:ledger => valid_attributes}, valid_session
        assigns(:ledger).should be_a(Ledger)
        assigns(:ledger).should be_persisted
      end

      it "redirects to the created ledger" do
        post :create, {:ledger => valid_attributes}, valid_session
        response.should redirect_to(Ledger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ledger as @ledger" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ledger.any_instance.stub(:save).and_return(false)
        post :create, {:ledger => {}}, valid_session
        assigns(:ledger).should be_a_new(Ledger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ledger.any_instance.stub(:save).and_return(false)
        post :create, {:ledger => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ledger" do
        ledger = Ledger.create! valid_attributes
        # Assuming there are no other ledgers in the database, this
        # specifies that the Ledger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ledger.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ledger.to_param, :ledger => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ledger as @ledger" do
        ledger = Ledger.create! valid_attributes
        put :update, {:id => ledger.to_param, :ledger => valid_attributes}, valid_session
        assigns(:ledger).should eq(ledger)
      end

      it "redirects to the ledger" do
        ledger = Ledger.create! valid_attributes
        put :update, {:id => ledger.to_param, :ledger => valid_attributes}, valid_session
        response.should redirect_to(ledger)
      end
    end

    describe "with invalid params" do
      it "assigns the ledger as @ledger" do
        ledger = Ledger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ledger.any_instance.stub(:save).and_return(false)
        put :update, {:id => ledger.to_param, :ledger => {}}, valid_session
        assigns(:ledger).should eq(ledger)
      end

      it "re-renders the 'edit' template" do
        ledger = Ledger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ledger.any_instance.stub(:save).and_return(false)
        put :update, {:id => ledger.to_param, :ledger => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ledger" do
      ledger = Ledger.create! valid_attributes
      expect {
        delete :destroy, {:id => ledger.to_param}, valid_session
      }.to change(Ledger, :count).by(-1)
    end

    it "redirects to the ledgers list" do
      ledger = Ledger.create! valid_attributes
      delete :destroy, {:id => ledger.to_param}, valid_session
      response.should redirect_to(ledgers_url)
    end
  end

end
